apiVersion: v1
kind: Service
metadata:
  name: bankly-service
  labels:
    app: bankly-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bankly-app 
  sessionAffinity: None
