apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNVEExTWpVeQpNekV4TWpkYUZ3MDBNVEExTWpVeU16RXhNamRhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDdXZya014MUxtZ1U4S3hPL1QzMzVSdURaQzlTMEkwbE5KOFBYcHJhRVZJUlFnUm8rcAp5eWljaVBxMGdXeVdXYXZhZ2FCcEgySlpTeFBlNkxMN3RXdGpVODRIQnNTZzk3UzUwRDZxbHV1YlpBazFFSzB6CjZGcUJ5eWJxMEJ5UjhlWkIrWFNEQmx5Q3A3NzZzYTNZUzhtd0xJT3p0VkthVS9VLzdHQnpDRXFDb1NEVTgwMGsKTHpzUVJxWWEvdFhYN09kZEJtME9HVVVaNEdBUE1qTm9GaW9ya1VXMjV6VVBDZzJiblhoQ1UzZHBZa2JqQi9Yago2Ly9xUlF3U0VFS1ZtT21LVDl5Z254Q2J4NE80c0JUVUQwbk1xaytmMkR4d21oRlhSN0dvcjdabXp5aUdvbnBLCnhtaWpCR0I1dXhmRGYvaS9aMDZlbWRjZVc0Y0NwMzNCRmtEdkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlIyRjB3VUNpa2RKQTdoclhuQwpNbWJuMFdLUjl6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFqTEk1NWJtSUQzQ1NWZkRzL3B4L0Z1Nk1MYWNqCnZXMGFJcDl5TmhXWThEckJyRllwMGp2czNNLzZjMFRyQjM3NE0wdEF2L1JsbStaTVFPWnFWd3lSZVd3VlVqOGEKSXhZWjEvVXVGVnFFWjRISDI0a2dMQnhVWWRZWTF2VUJOb2RtaG1ETlRJSnhCU2pwdWU5WU55UDBsanRsMC91dgpkampBbGM0TFA2QlhXd1dkaEs1c1pjUGVWZk9sYnk1akoyUzNTTzhSVFNnbU5SL041N3VSemRzRVhDMHNocFd4CmlXUGFrRXpTMEpjaWt0TzdQdXpLOUQrSFdISXhiWkVGYUdCbGhNVFdyRFZqcFQvOHBMNDRLb0MvUE5waUJsVSsKZElockxVbE84S2tTMlFPc280bEx5OE5hK05BMURvYzVsSS93enplZUVrcFJlNVRtT3BDcW1MQ2l6Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://063635c1-ee08-4ede-a7c8-a300f3155645.k8s.ondigitalocean.com
  name: do-nyc1-bankly
contexts:
- context:
    cluster: do-nyc1-bankly
    user: do-nyc1-bankly-admin
  name: do-nyc1-bankly
current-context: do-nyc1-bankly
kind: Config
preferences: {}
users:
- name: do-nyc1-bankly-admin
  user:
    token: ad57774c0b869bbe1835b39cbe052822423940c0f46aceea5aa9d1298bf7c1f6
