#!/bin/bash

# Example Usage: ./deploy v1.0

NAME_IMAGE="allenchen0223/bankly-server"
NAME_CONTAINER="bankly-server"

# Build docker image
sudo docker build -t $NAME_IMAGE:$1 .

sudo docker push $NAME_IMAGE:$1
# sudo docker ps -q --filter "name=$NAME_CONTAINER" | grep -q . && sudo docker stop $NAME_CONTAINER && sudo docker rm -fv $NAME_CONTAINER
# sudo docker run -d -p 5000:5000 --name bankly_server allenchen0223/bankly-server:v0.0
# sudo docker rm bankly_server -fv